server:
  servlet:
    context-path: /
  port: ${APP_PORT:8020}
spring:
  application:
    name: ${APP_NAME:yawn-service}
    version: 1.0.0
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  rabbitmq:
#    exchangeName: ${EXCHANGE_NAME:dev-platform-exchange}
#    queueNameDefault: ${QUEUE_NAME_DEFAULT:dev-platform.events}
#    routingKeyPrefix: ${ROUTING_KEY_PREFIX:dev-platform}
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: ${RABBIT_VHOST:/}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    connection-timeout: 1000ms
    template:
      default-receive-queue: yawn-service.queue
      exchange: ${RABBIT_EXCHANGE:dev-platform.exchange}
      custom:
        jira:
          routing-key-prefix: ${RABBIT_JIRA_ROUTINGKEY_PREFIX:dev-platform.jira}
        gitlab:
          routing-key-prefix: ${RABBIT_GITLAB_ROUTINGKEY_PREFIX:dev-platform.gitlab}
        slack:
          routing-key-prefix: ${RABBIT_SLACK_ROUTINGKEY_PREFIX:dev-platform.slack}
        
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
yawn:
  routingkey-prefix: ${RABBIT_ROUTINGKEY_PREFIX:dev-platform}
  gitlab:
    authentication-header-name: "x-gitlab-token"
    authentication-header-value: ${GITLAB_HEADER_NAME:12345678}